# mysql
spring:
  #配置数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_crud?characterEncoding=utf-8
    username: root
    password: 123456
    #使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      #正向工程，如果数据中没有表，则会创建一张表再更新数据，存在，则会直接更新数据
      ddl-auto: update
    #打印执行sql语句
    show-sql: true

# oracle
#spring:
#  jpa:
#    database: oracle
#    show-sql: true
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
#    username: ****
#    password: ****
